### ISSUE TITLE
Use krustlet as k3s node

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/fedra-thesis#23]

**Comment by jiayihu** [comment]
That went surprisingly well. The ARM64 binary is correctly working and all it needs is to:

1. Download the ARM64 Binary
2. [Generate](https://github.com/deislabs/krustlet/blob/master/docs/howto/bootstrapping.md) and copy the `bootstrap.conf` to the agents
3. Set the `KUBECONFIG` env variable
4. Run the binary as in the [bootstraping](https://github.com/deislabs/krustlet/blob/master/docs/howto/bootstrapping.md) doc

I believe the authentication flow could be simplified. K3s just needs the server token and to generate a password, without all the configuration done in `bootstrap.sh` and the `bootstrap.config` file.

**Comment by obeleh** [comment]
Hey @jiayihu did you also get this message or do you know what I might have done wrong?

```
KUBECONFIG=/etc/rancher/k3s/k3s.yaml   krustlet-wasi   --node-ip 127.0.0.1   --node-name=krustlet   --bootstrap-file=${HOME}/.krustlet/config/bootstrap.conf

Error: ApiError: the server could not find the requested resource: NotFound (ErrorResponse { status: "Failure", message: "the server could not find the requested resource", reason: "NotFound", code: 404 })

Caused by:
    the server could not find the requested resource: NotFound
```

**Comment by jiayihu** [comment]
Hey @obeleh you should probably ask in the Krustlet repository for support, it has been a long time since I've used it :)
